/* DO NOT EDIT THIS FILE - it is machine generated */
#include <string.h>
#include <jni.h>
#include "com_jayden_testandroid_ndk_HelloNDKActivity.h"
/* Header for class com_jayden_testandroid_ndk_HelloNDKActivity */

/*
 * Class:     com_jayden_testandroid_ndk_HelloNDKActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jayden_testandroid_ndk_HelloNDKActivity_getStringFromNative
  (JNIEnv * env, jobject obj) {
        return (*env)->NewStringUTF(env,"Hello From JNI!");
  }
