/* DO NOT EDIT THIS FILE - it is machine generated */
#include <string.h>
#include <jni.h>
/* Header for class com_jayden_testandroid_ndk_HelloNDKActivity */

#ifndef _Included_com_jayden_testandroid_ndk_HelloNDKActivity
#define _Included_com_jayden_testandroid_ndk_HelloNDKActivity
#ifdef __cplusplus
/*
 * Class:     com_jayden_testandroid_ndk_HelloNDKActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jayden_testandroid_ndk_HelloNDKActivity_getStringFromNative
  (JNIEnv * env, jobject obj) {
        return (*env)->NewStringUTF(env,"Hello From JNI!");
  }

#ifdef __cplusplus
}
#endif
#endif
