/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jayden_testandroid_ndk_HelloNDKActivity */

#ifndef _Included_com_jayden_testandroid_ndk_HelloNDKActivity
#define _Included_com_jayden_testandroid_ndk_HelloNDKActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jayden_testandroid_ndk_HelloNDKActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jayden_testandroid_ndk_HelloNDKActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
