/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jayden_testandroid_ndk_HelloNDKActivity */


extern "C" {
/*
 * Class:     com_jayden_testandroid_ndk_HelloNDKActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jayden_testandroid_ndk_HelloNDKActivity_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_jayden_testandroid_ndk_HelloNDKActivity
 * Method:    writeDataToFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jayden_testandroid_ndk_HelloNDKActivity_writeDataToFile
  (JNIEnv *, jobject, jstring);

}
