/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <string.h>
#include <jni.h>
#include "com_jayden_testandroid_ndk_HelloNDKActivity.h"
#include <android/log.h>
#define TAG "NativeMethod"
#define LOGV(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)
/* Header for class com_jayden_testandroid_ndk_HelloNDKActivity */

/*
 * Class:     com_jayden_testandroid_ndk_HelloNDKActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */

/*
 * Class:     com_jayden_testandroid_ndk_HelloNDKActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jayden_testandroid_ndk_HelloNDKActivity_getStringFromNative
  (JNIEnv * env, jobject obj) {
        return env->NewStringUTF("Hello From JNI!");
  }

JNIEXPORT void JNICALL Java_com_jayden_testandroid_ndk_HelloNDKActivity_writeDataToFile
  (JNIEnv *env, jobject jclas, jstring path){
  const char* file_path = env->GetStringUTFChars(path,NULL);//进行类型转换，jstring->char*
      if(file_path != NULL){
          LOGV("file_path in c %s",file_path);
      }

      //打开文件
      FILE* file = fopen(file_path,"a+");
      if(file != NULL){
          LOGV("open file success in c");
      }

      //写入文件
      char data[]="hello jni";
      int count = fwrite(data,strlen(data),1,file);
      if(count > 0){
          LOGV("write file success in c");
      }

      //关闭文件
      if(file != NULL){
          fclose(file);
      }

      //释放资源
      env->ReleaseStringUTFChars(path,file_path);
  }